### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by kanglaeheon** [kanglaeheon/practice-github-project-kanban#1]
### 만들고자 하는 기능?
Todo 생성 기능

### 할 일
1. [x] 생성 버튼 만들기
2. [x] FE : 생성 버튼 클릭시 서버에 POST 요청
3. [x] BE : POST 요청시 응답 전송
4. [x] 생성 버튼 CSS 작업

### 예상 작업 시간
3h
